[manager]
ratio = [1, 2, 3]

sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true

linemode = "size"
show_hidden = false
show_symlink = false

scrolloff = 255

[preview]
wrap = "no"
tab_size = 2
max_width = 1000  # yazi --clear-cache
max_height = 1500 # yazi --clear-cache
image_quality = 75
sixel_fiction = 15

# ueberzug_scale = 1.25 # change it to the Hyprland scale idk what this does
