# -----------------------------------------------------------------------------
# NH (Nix Home) Integration
# -----------------------------------------------------------------------------
#
# Reference: https://github.com/nix-community/nh
# Last updated: 2025-10-09
#
# -----------------------------------------------------------------------------
{ user, ... }: {
  programs.nh = {
    enable = true;  
    # Enables NH, the tool for managing dotfiles and user configurations via flakes.

    clean.enable = true;  
    # Enables the clean functionality for profiles/snapshots generated by NH.

    clean.extraArgs = "--keep-since 4d --keep 3";  
    # Extra arguments passed to the `nh clean` command:
    # --keep-since 4d → keep everything created in the last 4 days
    # --keep 3 → keep the last 3 generations/backups regardless of date
    # Note: these arguments only apply when running `nh clean`, not with `nixos-rebuild`.

    flake = "/home/${user}/.config/nixos-dotfiles/";  
    # Path to the dotfiles flake managed by NH. `${user}` is substituted with the username.
  };
}
